### ISSUE TITLE
custom timeout

### ISSUE THREAD

**Issue by Pasikonik** [windsorschmidt/disable-workspace-switcher-popup#10]
Do you have any idea how to set specific timeout?

**Comment by windsorschmidt** [comment]
Unfortunately this plugin doesn't support a timeout, since it entirely avoids the logic that displays the popup in the first place.

For changing the timeout I guess you'd have to bring in more of the original Gnome code displaying the popup and modify the timeout; maybe there is a more elegant Javascripty way to override just the timeout value. Feel free to fork this code, but I think the current functionality is complete and as-advertised, so I'll close this ticket. Thanks!
