### ISSUE TITLE
Extension not being listed for some gnome-shell versions

### ISSUE THREAD

**Issue by onreachable** [windsorschmidt/disable-workspace-switcher-popup#12]
This extension is not listed for me on the website and it's probably something related to my gnome-shell version, somehow the extensions website thinks it's not supported by 3.18...
![screenshot from 2016-03-27 16-47-56](https://cloud.githubusercontent.com/assets/1047033/14067517/7d2f2750-f43c-11e5-8a1d-ca2021cde180.png)

Perhaps you can set a supported version range in the extension metadata?!

**Comment by onreachable** [comment]
Version 3.18 [it's already in there](https://github.com/windsorschmidt/disable-workspace-switcher-popup/blob/master/metadata.json#L14), however since I'm unable to download from the website, I can't if this change is already published...

**Comment by windsorschmidt** [comment]
Unfortunately the extensions website interface is very basic, and doesn't show me (as the uploader of the extension) any details about the extension, so I can't check the version. :(

I may have simply (my mistake) not published the latest version on extensions.gnome.org. I've done that just now, but I don't know if/when they manually review uploads.

In the mean time, it's relatively easy to install the extension using gnome-tweak-tool. Just zip the contents of the repository here, and select the zip archive in gnome-tweak-tool's extensions pane. From the command-line, you can zip the archive with:

```
cd disable-workspace-switcher-popup
zip disable-workspace-switcher-popup.zip *
```

I'm closing the issue here, since this isn't a problem with the extension itself, rather it's availability on extensions.gnome.org. Feel free to open another issue here if you aren't able to install the extension manually. Thanks!
