### ISSUE TITLE
Add a new Gnome shell version

### ISSUE THREAD

**Issue by AndrewGYork** [windsorschmidt/disable-workspace-switcher-popup#24]
Stopped working for me, presumably because:
[user@localhost ~]$ gnome-shell --version
GNOME Shell 3.20.4
...which wasn't listed in metadata.json, so I added a line to metadata.json and restarted gnome-shell, which seemed to fix it. Is there a way to future-proof this? Or you just have to update every time gnome-shell updates?

**Comment by windsorschmidt** [comment]
Hiya. I've added GNOME Shell 3.20.4 in 173dc7c.

I'm curious, do you know if the previous version that *did* work for you was listed in the metadata.json file? I ask because don't know if z in version _x.yy.z_ is checked against the running version to decide if the plugin is loaded, or just _yy_. AFAIK having the versions listed in metadata.json is the proper way to tell GNOME that a plugin is compatible.

I'd love to know if there is a better, more future-proof way to handle this, but to my knowledge there isn't. The documentation on GNOME Shell extensions is unfortunately quite sparse. 🙁

Closing this one, but feel free to open an issue or pull request for version updates. I'm not actively using GNOME these days, so I won't notice if the plugin goes out of date. Thanks!
