### ISSUE TITLE
This should be on the official extensions site

### ISSUE THREAD

**Issue by danielquinn** [windsorschmidt/disable-workspace-switcher-popup#9]
A great extension, but I can't find it on [extensions.gnome.org](https://extensions.gnome.org/).  Is there any plan to put it there?

**Comment by windsorschmidt** [comment]
Good idea! I just uploaded it, but apparently it must be manually reviewed before it becomes available on the site.

**Comment by windsorschmidt** [comment]
Closing because the extension is now available on extensions.gnome.org.

**Comment by onreachable** [comment]
@windsorschmidt I wasn't able to find it... Maybe it's hidden due to my shell version (3.18)?!
Can you provide the link or under which name it is registered ?!

Meanwhile I'll install manually, thanks for sharing this one!

**Comment by windsorschmidt** [comment]
Using the search box on https://extensions.gnome.org entering the plugin by name, disable-workspace-switcher-popup, I was able to find it: https://extensions.gnome.org/extension/959/disable-workspace-switcher-popup/

Are you positive you've got 3.18 and not 3.20? 3.18 is already supported, but I see that 3.20 was released just hours ago, so this would be a big coincidence! You can make a new issue for adding 3.20 to the supported lists if it turns out you have 3.20. I will test and update either way. Thanks.

**Comment by onreachable** [comment]
Issue #12 filled...

As for updating to 3.20, it seems that fedora 23 (stable) will stick with 3.18. So I'm going to wait as well.
